Trigger management
apache/incubator-openwhisk-package-alarms pull request #101
Opened 2017-10-23 20:43 UTC by abaruni

this PR is for the fetching of the current configuration and status of a feed trigger

2017-10-23 20:56 UTC, abaruni commented
@csantanapr @jasonpet

2017-10-24 09:27 UTC, jthomas commented
Can the READ response be extended to include the `triggersLeft` value? 

Related to: https://github.com/apache/incubator-openwhisk/issues/1398

2017-10-24 13:53 UTC, jasonpet commented
Not sure how valid issue #1398 is anymore.  That was created before we set infinite triggers as the default for alarms.  The READ simply reads from the database and the triggers left is not stored in the database.  It is an in-memory count on the provider itself.  We really do not want to be doing database writes on every trigger fire.  We could try to read from a provider endpoint to get this value.  However, this is not trivial now that we have multiple provider instances (as part of our redundancy and load balancing support).  We would have to compute the endpoint url to use (by getting the worker id from the db first).

2017-10-24 16:17 UTC, jasonpet commented
@abaruni - the legacy alarms code created some trigger entries in the trigger database with a '_' for the namespace.  It was not until the creation of the __OW_NAMESPACE variable that we always started using the resolved namespace.  In your current implementation the lookup for READ would always use the resolved namespace and would never work for user's with older triggers who have '_' set for the namespace.  Please see how we handle DELETE and do the same thing for READ.

2017-10-24 16:38 UTC, jthomas commented
@jasonpet Thanks for explaining, I see the reasoning that this requirement is less valid with the infinity max triggers value. 

If the "triggers left" values are only stored in memory, does that mean in the event of a provider crash it's going to lose all that state?

2017-10-24 19:34 UTC, jasonpet commented
@jthomas - yes, on a crash we would lose state and the count would start back from the beginning (initial value of maxTriggers).  We are implementing a new alarms action that will fire until an end date and will then stop once that date has been reached.  This would be a more reliable option and give the user more control when creating a temporary alarms trigger.

2017-10-25 20:04 UTC, csantanapr requested changes

2017-10-25 20:04 UTC, csantanapr commented on provider/lib/utils.js
> +                        'dateChanged': Date.now(),
We want seconds not milliseconds , need to devide 1000 and round

2017-10-25 20:05 UTC, csantanapr commented on action/alarmWebAction.js
> +                        maxTriggers: doc.maxTriggers
Should we not include maxTriggers if we really want to deprecate them

2017-10-25 20:07 UTC, csantanapr commented
Need to handle how to deal when an old trigger has a different format for dateChange,

2017-10-31 17:28 UTC, jasonpet commented
Reviewed and tested most recent changes and they look good.

2017-11-01 14:32 UTC, csantanapr approved these changes

2017-11-01 14:34 UTC, merged